-- Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.chargers (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null default '',
  city text not null default '',
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  charger_type text not null default 'AC',
  connector_types text[] not null default '{}',
  power_kw numeric(7,2) check (power_kw >= 0),
  ports integer not null default 1 check (ports > 0),
  operator text,
  working_hours text not null default '24/7',
  price_info text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.chargers enable row level security;
drop policy if exists "Public can read active chargers" on public.chargers;
create policy "Public can read active chargers" on public.chargers for select using (is_active = true or auth.role() = 'authenticated');
drop policy if exists "Admin can insert chargers" on public.chargers;
create policy "Admin can insert chargers" on public.chargers for insert to authenticated with check (true);
drop policy if exists "Admin can update chargers" on public.chargers;
create policy "Admin can update chargers" on public.chargers for update to authenticated using (true) with check (true);
drop policy if exists "Admin can delete chargers" on public.chargers;
create policy "Admin can delete chargers" on public.chargers for delete to authenticated using (true);

drop trigger if exists chargers_set_updated_at on public.chargers;
create trigger chargers_set_updated_at before update on public.chargers for each row execute function public.set_updated_at();

create index if not exists chargers_active_idx on public.chargers (is_active);
create index if not exists chargers_location_idx on public.chargers (latitude,longitude);
