-- Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('charger','adapter','accessory')),
  category_label text not null default 'აქსესუარი',
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  description text not null default '',
  models text[] not null default '{}',
  badge text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select using (is_active = true or auth.role() = 'authenticated');
drop policy if exists "Authenticated admin can insert products" on public.products;
create policy "Authenticated admin can insert products" on public.products for insert to authenticated with check (true);
drop policy if exists "Authenticated admin can update products" on public.products;
create policy "Authenticated admin can update products" on public.products for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated admin can delete products" on public.products;
create policy "Authenticated admin can delete products" on public.products for delete to authenticated using (true);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('products','products',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "Public product images" on storage.objects;
create policy "Public product images" on storage.objects for select using (bucket_id='products');
drop policy if exists "Admin uploads product images" on storage.objects;
create policy "Admin uploads product images" on storage.objects for insert to authenticated with check (bucket_id='products');
drop policy if exists "Admin updates product images" on storage.objects;
create policy "Admin updates product images" on storage.objects for update to authenticated using (bucket_id='products');
drop policy if exists "Admin deletes product images" on storage.objects;
create policy "Admin deletes product images" on storage.objects for delete to authenticated using (bucket_id='products');
