(()=>{
const language=['ka','en','ru'].includes(localStorage.getItem('chargerx-language'))?localStorage.getItem('chargerx-language'):'ka';
const copy={
ka:{title:'ნავიგაცია — ChargerX',search:'მოძებნეთ მისამართი…',build:'მარშრუტის აგება',destination:'დანიშნულების ადგილი',arrival:'მისვლა',time:'დრო',distance:'მანძილი',routes:'სხვა მარშრუტები',close:'მარშრუტის დახურვა',continue:'გააგრძელეთ მარშრუტზე',next:'შემდეგ გააგრძელეთ მარშრუტზე',speed:'კმ/სთ',recenter:'მანქანაზე დაბრუნება',locate:'ჩემი მდებარეობა',map3d:'3D რუკა',traffic:'საცობების ჩვენება',night:'ღამის რეჟიმი',marker:'ლოკაციის ნიშნულის არჩევა',exit:'გასვლა',selected:'არჩეული ობიექტი',direction:'↗ მიმართულება',label:'ნიშნული',color:'ფერი ',arrow:'ისარი',autoDark:'ავტომატური ღამის რეჟიმი'},
en:{title:'Navigation — ChargerX',search:'Search for an address…',build:'Build route',destination:'Destination',arrival:'Arrival',time:'Time',distance:'Distance',routes:'Alternative routes',close:'Close route',continue:'Continue on the route',next:'Then continue on the route',speed:'km/h',recenter:'Recenter on vehicle',locate:'My location',map3d:'3D map',traffic:'Show traffic',night:'Night mode',marker:'Choose vehicle marker',exit:'Exit',selected:'Selected place',direction:'↗ Directions',label:'Vehicle',color:'Color ',arrow:'Arrow',autoDark:'Automatic dark mode'},
ru:{title:'Навигация — ChargerX',search:'Найти адрес…',build:'Построить маршрут',destination:'Пункт назначения',arrival:'Прибытие',time:'Время',distance:'Расстояние',routes:'Другие маршруты',close:'Закрыть маршрут',continue:'Продолжайте по маршруту',next:'Далее продолжайте по маршруту',speed:'км/ч',recenter:'Вернуться к автомобилю',locate:'Моё местоположение',map3d:'3D-карта',traffic:'Показать пробки',night:'Ночной режим',marker:'Выбрать маркер автомобиля',exit:'Выход',selected:'Выбранное место',direction:'↗ Маршрут',label:'Автомобиль',color:'Цвет ',arrow:'Стрелка',autoDark:'Автоматический ночной режим'}
}[language];
const text=(id,value)=>{const element=document.getElementById(id);if(element)element.textContent=value};
const attr=(id,name,value)=>document.getElementById(id)?.setAttribute(name,value);
function apply(){
document.documentElement.lang=language;document.title=copy.title;attr('destination','placeholder',copy.search);document.querySelector('#routeForm button')?.setAttribute('aria-label',copy.build);text('routeDestination',copy.destination);
const stats=document.querySelectorAll('#routeSummary>div>small');[copy.arrival,copy.time,copy.distance].forEach((value,index)=>{if(stats[index])stats[index].textContent=value});
text('moreRoutes',copy.routes);attr('closeRoute','aria-label',copy.close);text('maneuverText',copy.continue);text('maneuverNext',copy.next);const speed=document.querySelector('#speed small');if(speed)speed.textContent=copy.speed;
attr('locateButton','aria-label',copy.locate);attr('mode3dButton','aria-label',copy.map3d);attr('trafficButton','aria-label',copy.traffic);attr('themeButton','aria-label',copy.night);attr('markerPickerButton','aria-label',copy.marker);
const exit=document.querySelector('.map-actions a[href="/"]');if(exit){exit.textContent='EXIT';exit.setAttribute('aria-label',copy.exit)}const selected=document.querySelector('.place-card>small');if(selected)selected.textContent=copy.selected;text('placeDirections',copy.direction);
const picker=document.getElementById('markerPicker');if(picker){picker.setAttribute('aria-label',copy.marker);picker.firstElementChild.textContent=copy.label}attr('markerColor','aria-label',copy.color.trim());document.querySelector('[data-marker="arrow"]')?.setAttribute('title',copy.arrow);const color=document.querySelector('.marker-color');if(color?.firstChild)color.firstChild.nodeValue=copy.color;const autoDark=document.querySelector('.auto-dark-setting span');if(autoDark)autoDark.textContent=copy.autoDark;
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',apply):apply();
window.addEventListener('storage',event=>{if(event.key==='chargerx-language'&&event.newValue!==language)location.reload()});
})();
